### ISSUE TITLE
Crash when joining voice channel or playing sounds

### ISSUE THREAD

**Issue by jschenke488** [Aliucord/AliucordRN#37]
This has been reported in the Discord server, but when any sound plays, including joining a voice channel, Discord crashes. When reopened, it either shows this screen or instantly crashes again until the app is force stopped.
![Screenshot_20221009_004553](https://user-images.githubusercontent.com/44783760/194775911-17db3fc4-944c-4381-9ede-55f705a79163.jpg)
If reload is pressed, it displays this.
![Screenshot_20221009-142202](https://user-images.githubusercontent.com/44783760/194775933-f1d0325f-8017-40e5-b9e3-24ace9ac27b3.jpg)

**Comment by AAGaming00** [comment]
:trollface: we literally just found this an hour ago

**Comment by Vendicated** [comment]
https://discord.com/channels/811255666990907402/925873645593722970/1028735052382740520

**Comment by DiamondMiner88** [comment]
Fixed in https://github.com/Aliucord/AliucordNative/commit/82e9a298adea42eae8d99e7caf4d2171b6c37ab9
