### ISSUE TITLE
[Bug] Broken AMOLED mode

### ISSUE THREAD

**Issue by Henry-Hiles** [Aliucord/AliucordRN#39]
At first when you turn on AMOLED mode in AliucordRN, everything works as expected. However, after a restart, only some elements have AMOLED applied.

**Comment by Austcool-Walker** [comment]
> At first when you turn on AMOLED mode in AliucordRN, everything works as expected. However, after a restart, only some elements have AMOLED applied.

I can confirm this is a error for me as well.

**Comment by NightNutSky** [comment]
Yeah

**Comment by MatadorProBr** [comment]
Probably this issue could be closed now since it's fixed?

**Comment by rushiiMachine** [comment]
Fixed by #42
